export const GET_LESSONS = 'GET_LESSONS';
export const ADD_LESSON = 'ADD_LESSON';
export const DELETE_LESSON = 'DELETE_LESSON';
export const LESSONS_LOADING = 'LESSONS_LOADING';
export const LESSON_FAIL='LESSON_FAIL';

export const USER_LOADING='USER_LOADING';
export const USER_LOADED='USER_LOADED';
export const AUTH_ERROR='AUTH_ERROR';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';
export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_FAIL='REGISTER_FAIL';
export const GET_ERRORS='GET_ERRORS';
export const CLEAR_ERRORS='CLEAR_ERRORS';